---
- name: ansible installation
  hosts: all
  remote_user: ubuntu
  become: true
  tasks:
  
  - name: Create directories for deployment and playbook configs
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
    loop:
      - /home/ubuntu/deployment
      - /home/ubuntu/playbook  

  - name: Copy required files to the deployment directory
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}/"
      mode: "{{ item.mode | default('0644') }}"
      owner: ubuntu
      group: ubuntu
    loop:
      - { src: "./docker-compose.yaml", dest: "/home/ubuntu/deployment" }
      - { src: "./.env", dest: "/home/ubuntu/deployment" }
      - { src: "./inventory.aws_ec2.yaml", dest: "/home/ubuntu/playbook" }
      - { src: "./ansible-config/ansible.cfg", dest: "/home/ubuntu/playbook" }
      - { src: "./main-deployment-playbook.yaml", dest: "/home/ubuntu/playbook" } 
      - { src: "./inventory.ini", dest: "/home/ubuntu/playbook" }
      - { src: "~/.ssh/aws-keypair", dest: "/home/ubuntu/playbook" , mode: "0400" } # change the path with your own PEM key

  - name: Run the playbook command
    ansible.builtin.command: ansible-playbook -i inventory.ini main-deployment-playbook.yaml
    args:
      chdir: /home/ubuntu/playbook
    register: result
