---
- name: Ansible Installation and Deployment
  hosts: all
  become: true
  tasks:
  
  - name: Update apt cache
    ansible.builtin.apt:
      update_cache: yes   

  - name: Install required packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop:
      - docker.io
      - docker-compose  

  - name: Add ubuntu user to the docker group
    ansible.builtin.user:
      name: ubuntu
      groups: docker
      append: yes    

  - name: Create deployment directory
    ansible.builtin.file:
      path: /home/ubuntu/app-deployment
      state: directory
      mode: '0755'
      owner: ubuntu
      group: ubuntu

  - name: Copy docker-compose and env files to deployment directory
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/home/ubuntu/app-deployment/"
      mode: '0644'
      owner: ubuntu
      group: ubuntu
    loop:
      - "/home/ubuntu/deployment/docker-compose.yaml"
      - "/home/ubuntu/deployment/.env"

  - name: Run docker-compose up
    community.docker.docker_compose:
      project_src: /home/ubuntu/app-deployment
      state: present
